import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chep0x61's Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-[#f8f8f8] dark:bg-[#1a1a1a] color-[#1a1a1a] dark:color[#f8f8f8]">
      <Providers>
        <main className={inter.className}>{children}</main>
      </Providers>
      </body>
    </html>
  );
}
