name: Backend Docker Compose Build Step

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Build docker
        run: docker-compose build

      - name: Build and start Docker services
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 30

      - name: Stop Docker services
        run: docker-compose down